//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GayMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GayMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ///////////////////////////////
        ///// PlayStation Vita specific
        //////////////////////////////////
        ///
        ///// # = constant
        ///// * = readonly
        ///// &amp; = obsolete
        ///
        ///psn_get_leaderboard_score_range(pad_index, leaderboard_id, start_index, end_index)
        ///psn_default_user_name()
        ///psn_name_for_pad(pad_index)
        ///psn_unlock_trophy(pad_index, trophy_index)
        ///psn_get_trophy_unlock_state(pad_index)
        ///psn_init_np_libs(title_id, np_title_secret, np_passphrase, enable_online)
        ///psn_exit_np_libs()
        ///psn_get_leaderboard_score(pad_index, leaderboard_id)
        ///psn_po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fnames {
            get {
                return ResourceManager.GetString("fnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gate {
            get {
                object obj = ResourceManager.GetObject("Gate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;livearea style=&quot;psmobile&quot; format-ver=&quot;01.00&quot; content-rev=&quot;1&quot;&gt;
        ///	&lt;livearea-background&gt;
        ///		&lt;image&gt;bg0.png&lt;/image&gt;
        ///	&lt;/livearea-background&gt;
        ///	
        ///	&lt;gate&gt;
        ///		&lt;startup-image&gt;startup.png&lt;/startup-image&gt;
        ///	&lt;/gate&gt;
        ///
        ///	&lt;frame id=&quot;frame1&quot;&gt;
        ///	&lt;/frame&gt;
        ///	
        ///	&lt;frame id=&quot;frame2&quot;&gt;
        ///	&lt;/frame&gt;
        ///	
        ///	&lt;frame id=&quot;frame3&quot;&gt;
        ///	&lt;/frame&gt;
        ///	
        ///	&lt;frame id=&quot;frame4&quot;&gt;
        ///	&lt;/frame&gt;
        ///
        ///&lt;/livearea&gt;
        ///
        ///
        ///.
        /// </summary>
        internal static string gdbTemplate {
            get {
                return ResourceManager.GetString("gdbTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons {
            get {
                object obj = ResourceManager.GetObject("Icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
